# Generated by Django 4.2.3 on 2023-07-25 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leveltest', '0002_test_remove_response_answer_remove_response_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': 'Test'},
        ),
    ]
