# Generated by Django 4.2.3 on 2023-07-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='appinfo',
            options={'verbose_name_plural': 'AppInfo'},
        ),
        migrations.AlterModelOptions(
            name='applevel',
            options={'verbose_name_plural': 'AppLevel'},
        ),
        migrations.RemoveField(
            model_name='appinfo',
            name='field',
        ),
        migrations.AddField(
            model_name='appinfo',
            name='field',
            field=models.ManyToManyField(related_name='tag', to='applist.categorytag'),
        ),
    ]
