# Generated by Django 4.2.3 on 2023-07-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applist', '0003_phonemodel_appinfo_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appinfo',
            options={'verbose_name_plural': 'App Info'},
        ),
        migrations.AlterModelOptions(
            name='applevel',
            options={'verbose_name_plural': 'App Level'},
        ),
        migrations.AlterModelOptions(
            name='categorytag',
            options={'verbose_name_plural': 'Category Tags'},
        ),
        migrations.AlterModelOptions(
            name='phonemodel',
            options={'verbose_name_plural': 'Phone Model'},
        ),
        migrations.RemoveField(
            model_name='appinfo',
            name='link',
        ),
        migrations.AddField(
            model_name='appinfo',
            name='alink',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appinfo',
            name='slink',
            field=models.TextField(null=True),
        ),
    ]
