# Generated by Django 4.2.3 on 2023-07-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applist', '0004_alter_appinfo_options_alter_applevel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='alink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='slink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
