# Generated by Django 4.2.3 on 2023-08-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applist', '0005_alter_appinfo_alink_alter_appinfo_slink'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinfo',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
